name: docs

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: 1.1.6

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.in-project true

      - name: Set up cache
        uses: actions/cache@v2.1.6
        with:
          path: .venv
          key: ${{ matrix.platform }}-venv-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Get the release version
        run: |
          export RELEASE_TAG_VERSION=${{ github.event.release.tag_name }}
          echo "RELEASE_TAG_VERSION=${RELEASE_TAG_VERSION:1}" >> $GITHUB_ENV

      - name: Configure git
        run: |
          git config --global user.name Docs deploy
          git config --global user.email docs@dummy.bot.com

      - name: Publish the documentation
        run: |
          poetry run python -m mike deploy --push --update-aliases ${RELEASE_TAG_VERSION} latest
          poetry run python -m mike set-default --push latest
