name: Generate Changelog

on:
  pull_request:
    branches:
      - master
    types: [ opened, reopened ]
    paths-ignore:
      - '**.md'

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.6

      - name: Get the project's current version
        run: |
          VERSION="$(poetry version -s)"

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: v${{ env.RELEASE_VERSION }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated the Changelog
