name: Publish

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Publish to PyPI
        uses: JRubics/poetry-publish@v1
        with:
          pypi_token: ${{ secrets.DOTIFY_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Poetry
        uses: snok/install-poetry@v1.1.3

      - name: Get the project's current version
        run: |
          VERSION="$(poetry version -s)"

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Publish a new Release
        uses: fregante/release-with-changelog@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ env.RELEASE_VERSION }}
