name: Publish

on:
    pull_request:
        branches:
            - master
        types:
            - closed

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            - name: Create a GitHub Release
              uses: relekang/python-semantic-release@v7.15.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Publish to PyPI
              uses: JRubics/poetry-publish@v1
              with:
                pypi_token: ${{ secrets.DOTIFY_TOKEN }}
